<?php
return [
    'bsVersion' => '4.x',
    //'bsDependencyEnabled' => false,
    'adminEmail' => 'admin@example.com',
    'REST_API_URL'=>'http://localhost/advanced/restapi/v1/',
    "LOGO"=>'/images/logo.png',
    "FAVICON"=>'/sidebar/icons/logo_ic.svg',
    "SHORT_LOGO"=>'/sidebar/icons/logo_ic.svg',
    "DEFAULT_ERROR_IMG"=>'/images/svg/alert_image.svg',
    "DEFAULT_ATTACHMENT_IMG"=>'/images/svg/file_attach.svg',
    "DEFAULT_FILE_IMG"=>'/images/svg/file.png',
    "DEFAULT_USER_IMG"=>'/images/svg/default_user.png',
    "DEFAULT_NOT_AVAILABLE_IMG"=>'/images/svg/no_img_available.svg',
    "DEFAULT_CHEQUE_IMG"=>'/images/chaque/chaque.png',
    "DEFAULT_CHEQUEFILE_IMG"=>'/images/cheque/chequefile.png',
    "DEFAULT_MAP_IMG"=>'/images/svg/map.svg',
    "DEFAULT_BELOCUM_CLINIC_IMG"=>'/images/pages/user_icon.svg',
    "DEFAULT_BELOCUM_USER_IMG"=>'/images/pages/user_icon.svg',
    "GOOOGLE_LOGO"=>'/images/logo/ic_googlecolorfull.png',
    "CHAT_LOGO"=>'/images/icon/ic_chat_bubble.png',
    'IMAGE_EXTENTION'=>array("jpg","jpeg","png",'bmp'),
    'CHEQUE_EXTENTION'=>array("doc","docx","xls","xlsx","csv","ppt","pdf","DOC","DOCX","XLS","XLSX","CSV","PPT","PDF"),
    'VIDEO_EXTENTION'=>array('mp4','3gp', 'mov', 'm4v', 'mpg', 'flv','avi','mkv','wmv','webm'),
    'DOCUMENT_EXTENTION'=>array('doc','docx', 'xls', 'xlsx', 'ppt', 'pptx','pdf'),
    'DEFAULT_START_TIME'=>"08:00",
    'DEFAULT_END_TIME'=>"17:00",
    'TIME_FORMAT'=>"HH:mm",
    'DATE_FORMAT'=>"YYYY-MM-DD",
    'DATE_FORMAT_DATEPICKER'=>"yyyy-mm-dd",
    'DATETIME_FORMAT_DATETIMEPICKER'=>"yyyy-mm-dd hh:ii:ss",
    'TIME_FORMAT_TIMEPICKER'=>"HH:mm",
    'DATETIME_FORMAT'=>"YYYY-MM-DD HH:mm",
    'STEPPING'=>1, //Miniute time
    'STEPPINGCHANGE'=>1, //Miniute time
    'PLACEHOLDER_TIME_FORMAT'=>"HH:mm",
    'PLACEHOLDER_DATE_FORMAT'=>"YYYY-MM-DD",
    'PLACEHOLDER_DATETIME_FORMAT'=>"YYYY-MM-DD HH:mm",
    'PHP_DATE_FORMAT'=>"Y-m-d",
    'PHP_TIME_FORMAT'=>"H:i",
    'VERSION'=>"2.2.3",
    'MIN-WORDS'=>5,
    'MAX-WORDS'=>100,
    'MIN-CHARACTER'=>5,
    'MAX-CHARACTER'=>100,
    'APPEND-MAX-FIELD'=>5,
    'APPEND-MAX-ATTACHMENT'=>5,
    'APPEND-MAX-ITEM'=>5,
    'APPEND-MAX-WORKEXP'=>10,
    'APPEND-MAX-ESTABLISHMNET-CONTACT-PERSON'=>10,
    'MIN-DYNAMIC-FORM'=>1,
    'MIN-DYNAMIC-FORM0'=>0,
    "DATA-MAX-OPTIONS"=>1,
    'POPUP_TIME_MINIUTE'=> 240, // minuite
    "MIN-AGE-YEAR"=>"-18y",
    "BTNOKURL-NOTAPPROVED"=>array(
        'en'=>'https://calendly.com/belocumcanada/interview',
        'fr'=>'https://calendly.com/git/staging_ca_web/introduction',
    ), 
    "ADDRESS-ON-MAP"=>"http://maps.google.com/maps?daddr={clinic_latitude},{clinic_longitude}",
    "LANGUAGE_ICON"=>[
        'en'=>'images/pages/united-states.png',
        'fr'=>'images/pages/france.png',
    ],
];
